export const debtsTypes = {
    GET_ALL: "GET_ALL_DEBTS",
    REMOVE_ITEM: "REMOVE_ITEM_DEBTS",
    DISABLE_ITEM: "DISABLE_ITEM_DEBTS",
    ADD_ITEM: "ADD_ITEM_DEBTS",
    UPDATE_ITEM: "UPDATE_ITEM_DEBTS",
}