export const fixedCostsTypes = {
    GET_ALL: "GET_ALL_FIXED_COSTS ",
    REMOVE_ITEM: "REMOVE_FIXED_COSTS",
    DISABLE_ITEM: "DISABLE_FIXED_COSTS",
    ADD_ITEM: "ADD_FIXED_COSTS",
    UPDATE_ITEM_FIXED_COSTS: "UPDATE_ITEM_FIXED_COSTS",
}