export const necessaryTypes = {
    GET_ALL_NECESSARY : "GET_ALL_NECESSARY ",
    ADD_ITEM_NECESSARY: "ADD_ITEM_NECESSARY",
    REMOVE_ITEM_NECESSARY: "REMOVE_ITEM_NECESSARY",
    UPDATE_ITEM_NECESSARY: "UPDATE_ITEM_NECESSARY",
}