export const profitsTypes = {
    GET_ALL_PROFITS: "GET_ALL_PROFITS",
    DISABLE_ITEM_PROFITS: "DISABLE_ITEM_PROFITS",
    UPDATE_ITEM_PROFITS: "UPDATE_ITEM_PROFITS",
    ADD_ITEM_PROFITS: "ADD_ITEM_PROFITS",
    DELETE_ITEM_PROFITS: "DELETE_ITEM_PROFITS",
}