export const VolunteerThingsTypes = {
    GET_ALL: "GET_ALL_VOLUNTEER_THINGS",
    REMOVE_ITEM: "REMOVE_VOLUNTEER_THINGS",
    UPDATE_ITEM: "UPDATE_VOLUNTEER_THINGS",
    ADD_ITEM: "ADD_VOLUNTEER_THINGS"
}